# Generated by cucumber-sinatra. (2013-08-14 15:14:21 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'main.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'


Capybara.app = TTTDuet

`python /Users/arlandislawrence/development/python/tic_tac_toe/network_io/start_server.py &>log.txt &`

class MyAppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MyAppWorld.new
end
